# Generated by Django 4.2.5 on 2024-05-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapi', '0002_employee_is_adminapproved_hr_is_adminapproved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('hr', 'hr'), ('employee', 'employee'), ('teamlead', 'teamlead')], max_length=50),
        ),
    ]
