# Generated by Django 4.2.5 on 2024-07-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapi', '0003_remove_performance_assign_hr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='file',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
