# Generated by Django 4.2.5 on 2024-07-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapi', '0004_dailytask_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='file',
        ),
        migrations.AddField(
            model_name='dailytask',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='project_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
