# Generated by Django 4.2.5 on 2024-07-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapi', '0005_remove_projectdetail_file_dailytask_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
