# Generated by Django 4.2.5 on 2024-05-08 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrapi', '0006_rename_message_time_meeting_posted_at_meeting_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
