# Generated by Django 4.2.5 on 2024-05-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapi', '0008_technologieslist_rating_dailytask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='description',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='member',
        ),
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
